name: tripasammkt
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.1+1
  curved_navigation_bar: ^1.0.6
  water_drop_nav_bar: ^2.2.2
  crystal_navigation_bar: ^1.0.0
  text_scroll: ^0.2.0
  flashy_tab_bar2: ^0.0.10
  draggable_home: ^1.0.5
  dot_curved_bottom_nav: ^0.0.2
  url_launcher: ^6.1.5
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.3.2
  animated_custom_dropdown: ^3.1.1
  logger: ^2.4.0
  intl: ^0.19.0
  syncfusion_flutter_datepicker: ^27.1.51
  day_night_time_picker: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Artboard.png
    - assets/Artboard1.png
    - assets/Artboardx.png
    - assets/Artboardy.png
    - assets/Artboardz.png
    - assets/Artboarda.png
    - assets/Artboardb.png
    - assets/Artboardc.png
    - assets/Artboard.svg
    - assets/logo.png
    - assets/cloud.png
    - assets/graph.png
    - assets/Sun.png
    - assets/Moon.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Thin.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
